import { Router } from 'express';
import AppController from '../controllers/AppController';
import UsersController from '../controllers/UsersController';
import AuthController from '../controllers/AuthController';
import FileController from '../controllers/FilesController';

const routes = Router();
routes.get('/status', AppController.getStatus);
routes.get('/stats', AppController.getStats);
routes.post('/users', UsersController.postNew);
routes.get('/connect', AuthController.getConnect);
routes.get('/disconnect', AuthController.getDisconnect);
routes.get('/users/me', UsersController.getMe);
routes.post('/files', FileController.postUpload);
routes.get('/files/:id', FileController.getShow);
routes.get('/files', FileController.getIndex);
routes.put('/files/:id/publish', FileController.putPublish);
routes.put('/files/:id/unpublish', FileController.putUnpublish);
routes.get('/files/:id/data', FileController.getFile);
export default routes;
